spring:
  profiles:
    include: domain
  jpa:
    hibernate:
      ddl-auto: validate
#    show-sql: true
    properties:
      hibernate:
        format_sql: true
    open-in-view: true
  jackson:
    deserialization:
      fail-on-null-for-primitives: true

management:
  endpoints:
    web:
      exposure:
        include: env

kakao:
  client_id: 70b5d2ebdeab88e65b4caa45fa39df78
  redirect_uri: http://localhost:8080/login/kakao/callback